import AccountRepo from "@modules/auth/core/app/ports/AccountRepo";
import PasswordHasher from "@modules/auth/core/app/ports/PasswordHasher";
import RandomSecretGenerator from "@modules/auth/core/app/ports/RandomSecretGenerator";
import UnitOfWork, { AuthUoWContext } from "@modules/auth/core/app/ports/UnitOfWork";
import VerificationMailer from "@modules/auth/core/app/ports/VerificationMailer";
import RegisterMemberAccountUseCase from "@modules/auth/core/app/use-cases/account/RegisterMemberAccountUseCase";
import Account from "@modules/auth/core/domain/entities/Account";
import AccountRole from "@modules/auth/core/domain/value-objects/AccountRole";
import FullName from "@modules/auth/core/domain/value-objects/FullName";
import Email from "@shared/core/domain/value-objects/email/Email";
import { describe, expect, it } from "vitest";

describe("RegisterMemberAccountUseCase", () => {
    it("sends the password generated by its port to the new member", async () => {
        const actor = Account.register({
            id:           "admin-1",
            email:        Email.create("admin@soosky.vn"),
            passwordHash: "stored-hash",
            fullName:     FullName.create("System Admin"),
            role:         AccountRole.ADMIN,
            mustChangePassword: false,
        });
        const savedAccounts: Account[] = [];
        const sentPasswords: string[] = [];
        const accountRepo: AccountRepo = {
            getById: async id => id === actor.id ? actor : null,
            getByEmail: async () => null,
            existsByEmail: async () => false,
            existsByRole: async () => false,
            list: async () => [],
            save: async account => { savedAccounts.push(account); },
            deleteById: async () => undefined,
        };
        const context: AuthUoWContext = {
            accountRepo,
            refreshTokenStore: {
                issue: async () => ({ token: "refresh", expiresAt: new Date() }),
                consume: async () => null,
                revoke: async () => undefined,
                revokeAllForAccount: async () => undefined,
            },
            verificationTokenStore: {
                issue: async () => ({ token: "verification", expiresAt: new Date() }),
                consume: async () => null,
                revokeAllForAccount: async () => undefined,
            },
        };
        const unitOfWork: UnitOfWork = { run: work => work(context) };
        const passwordHasher: PasswordHasher = {
            hash: async password => `hash:${password}`,
            verify: async () => false,
        };
        const verificationMailer: VerificationMailer = {
            sendVerificationMail: async (_recipient, password) => { sentPasswords.push(password); },
        };
        const secretGenerator: RandomSecretGenerator = {
            generate: () => "initial-password",
        };
        const useCase = new RegisterMemberAccountUseCase(
            unitOfWork,
            passwordHasher,
            verificationMailer,
            secretGenerator,
        );

        const account = await useCase.execute({
            email:          "member@soosky.vn",
            fullName:       "Member One",
            actorAccountId: actor.id,
        });

        expect(account.passwordHash).toBe("hash:initial-password");
        expect(savedAccounts).toEqual([account]);
        expect(sentPasswords).toEqual(["initial-password"]);
    });
});
